{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "c544fd88",
   "metadata": {},
   "source": [
    "# Tasting For Wine Quality<br>\n",
    "## Project Description<br>\n",
    "For this project we will be gathering some wine data, analyzing it for particular features that will later be used as drivers for wine quality. \n",
    "We will project is to analyze the data, find driving features of wine quality, predict quality of wine, and recommend actions to produce good quality of wine.\n",
    "\n",
    "## Project Goals<br>\n",
    "- Discover drivers of quality\n",
    "- Use drivers to develop a machine learning model that accurately predicts wine quality\n",
    "- This information could be used on future datasets to help find high quality wine\n",
    "\n",
    "## Initial Questions<br>\n",
    "- Does wine color affect wine quality?\n",
    "- Does a higher quality mean higher alcohol content?\n",
    "- Is there a relationship between Citric Acid and Quality?\n",
    "- Is there a relationship between Free Sulfur Dioxide and Quality?\n",
    "\n",
    "## The Plan<br>\n",
    "#### Acquire data\n",
    "- Data aquired Data.World\n",
    "- Red wine containted 1599 rows × 12 columns and white wine contained 4898 rows × 13 columns before cleaning and concatenating\n",
    "- Each row represents a wine\n",
    "- Each column represents a feature associated with the wine\n",
    "\n",
    "#### Prepare\n",
    "- Renamed colums to read pythonic\n",
    "- Checked for nulls and outliers\n",
    "- Checked that column data types were appropriate and had to change as necessary\n",
    "- Added column after concatenating to clarify whether it is a red or white wine\n",
    "- Split data into train, validate and test, stratifying on 'quality'\n",
    "\n",
    "#### Explore data in search of drivers of quality and answer the following questions:\n",
    "- Does wine color affect wine quality?\n",
    "- Does a higher quality mean higher alcohol content?\n",
    "- Is there a relationship between Citric Acid and Quality?\n",
    "- Is there a relationship between Free Sulfur Dioxide and Quality?\n",
    "\n",
    "## Data Dictionary<br>\n",
    "| Name                 | Definition |\n",
    "| -------------------- | ---------- |\n",
    "| fixed acidity        | Specifies the fixed acidity of the wine |\n",
    "| volatile acidity     | Specifies the volatile acidity of the wine |\n",
    "| citric acid          | Specifies the citric acid of the wine |\n",
    "| residual sugar       | Specifies the residual sugar of the wine |\n",
    "| chlorides            | Specifies the chlorides of the wine |\n",
    "| free sulfur dioxide  | Specifies the free sulfur dioxide of the wine |\n",
    "| total sulfur dioxide | Specifies the total sulfur dioxide of the wine |\n",
    "| density              | Specifies the density of the wine |\n",
    "| pH                   | Specifies the pH of the wine |\n",
    "| sulphates            | Specifies the sulphates of the wine |\n",
    "| alcohol              | Specifies the alcohol of the wine |\n",
    "| quality              | Scale 1-10, specifies quality of wine |\n",
    "| wine_color           | Red or white, specifies color of wine | <br>\n",
    "\n",
    "## Steps to Reproduce\n",
    "- Clone this repo.\n",
    "- Acquire the data from Data.World\n",
    "- Put the data in the file containing the cloned repo.\n",
    "- Run notebook.\n",
    "\n",
    "## Takeaways and Conclusions\n",
    "\n",
    "- Wine color is not a big driver of quality\n",
    "- Alcohol is the biggest driver of quality\n",
    "- Free sulfur dioxide and citric acid were also not big drivers\n",
    "- Clustering did show us a similar plot to to one of our questions, but nothing particularly interesting\n",
    "\n",
    "## Recommendations\n",
    "- Focus more on investigation of sulfur content in soil due to correlation to quality\n",
    "- Get a more robust dataset with red wine\n",
    "- Add a feature such as vineyard or location to investigate higher rated wines\n",
    "- If provided more time to work on this project we would take a longer look at subetting on hyperparameters, clustering, and modeling on just white wine as it was a more robust dataset \n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
